apiVersion: threefs.aliyun.com/v1
kind: ThreeFsCluster
metadata:
  labels:
    threefs.aliyun.com/debug-mode: "true"
  name: tfsc-sample
spec:
  chainTableId: "1" # 此处当前固定设置
  stripeSize: 16    # 按需调整
  chunkSize: 1048576  # 按需调整
  filterList: ["bond0"]  # 选用网卡
  deviceFilter: ["mlx5_bond_0"] # 选用ib网卡
  fdb:
    configureNew: true
    storageReplicas: 2 # 表示fdb数据库中数据的副本数，推荐设为2~3
    clusterSize: 3 # 表示从fdb nodes中随机挑选对应数目的节点，组成fdb集群，遵循fdb官方推荐，强制约束clusterSize>=2*n-1，
    port: 4500
  clickhouse:
    nodes: ["node1"]
    db: "3fs"       # 此处当前固定设置
    user: "default" # 此处当前固定设置
    password: ""    # 此处当前固定设置
    tcpPort: 8999
  monitor:
    port: 10000
  mgmtd:
    rdmaPort: 8000
    tcpPort: 9000
    replica: 2 # 表示从storage nodes中随机挑选对应数目的节点启动多实例mgmtd服务
  meta:
    rdmaPort: 8001
    tcpPort: 9001
    replica: 2 # 表示从storage nodes中随机挑选对应数目的节点启动多实例meta服务
  storage:
    rdmaPort: 8002
    tcpPort: 9002
    replica: 2 # 数据多副本
    targetPaths: # 理论上这里每个挂载路径对应一个独立的 nvme 磁盘
      - "/storage/data0/3fs"
      - "/storage/data1/3fs"
      - "/storage/data2/3fs"
      - "/storage/data3/3fs"
    # 作用: 并发提升, 通过在单块物理盘上创建多个 Target, 可以增加并发队列的数量, 充分利用高性能  NVMe SSD 的 IO 深度
    # Chain 的构建: 3fs 将不同节点上的 Target 组合成 Chain (复制组), Target 数量越多, 能组成的 Chain 就越多, 允许的 StripeSize 也就越大
    targetPerDisk: 16 # 表示在每个 targetPath 下逻辑上划分出多少个 Target, Target 是存储服务的最小管理单元, 可以理解成磁盘上的分区或分片(目录形式存在)
    resources:
      limits:
        cpu: "4"
        memory: 20Gi
      requests:
        cpu: "2"
        memory: 10Gi